import { readFile, writeFile, mkdir } from 'node:fs/promises';
const root = new URL('../', import.meta.url);
const read = name => readFile(new URL(name, root), 'utf8');
let html = await read('index.html');
const css = await read('styles.css');
const config = (await read('site-config.js')).replace(/^export /gm, '');
const enquiry = (await read('enquiry.js')).replace(/^export /gm, '');
const app = (await read('app.js')).replace(/^import .+;\n/gm, '');
const script = (config + '\n' + enquiry + '\n' + app).replace(/<\/script/gi, '<\\/script');
const image = (await readFile(new URL('assets/hero-illustration.png', root))).toString('base64');
const favicon = (await readFile(new URL('assets/favicon.svg', root))).toString('base64');
html = html.replace('<link rel="stylesheet" href="./styles.css">', () => '<style>\n' + css + '\n</style>');
html = html.replace('<script type="module" src="./app.js"></script>', () => '<script type="module">\n' + script + '\n</script>');
html = html.replace('src="./assets/hero-illustration.png"', 'src="data:image/png;base64,' + image + '"');
html = html.replace('href="./assets/favicon.svg"', 'href="data:image/svg+xml;base64,' + favicon + '"');
await mkdir(new URL('dist/', root), { recursive: true });
await writeFile(new URL('dist/curavesta-preview.html', root), html);
console.log('Standalone preview: curavesta/dist/curavesta-preview.html');
